### ISSUE TITLE
Qrefine installation issue

### ISSUE THREAD

**Issue by rajeevroy09** [qrefine/qrefine#50] opened 2019-07-25 13:47 UTC
Hi,

I have tried multiple times to install qrefine as it is suggested at this page "https://github.com/qrefine/qrefine/blob/master/README.md" but the installation is throwing some error, which I am pasting below for your reference. It would be really nice if you guys help me with the installation.

=======================Error=========================================
Installing numpy 1.15.4...
NumPy is the fundamental package for array computing with Python.
  log file is /scratch/roy/programs/phenix-1.16-3549/base_tmp/numpy_install_log
  verifying numpy installation in /scratch/roy/programs/phenix-1.16-3549/base/bin/pythonTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch/roy/programs/phenix-1.16-3549/conda_base/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/scratch/roy/programs/phenix-1.16-3549/conda_base/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/scratch/roy/programs/phenix-1.16-3549/conda_base/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/scratch/roy/programs/phenix-1.16-3549/conda_base/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/scratch/roy/programs/phenix-1.16-3549/conda_base/lib/python2.7/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /scratch/roy/programs/phenix-1.16-3549/conda_base/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS4_FromObject

Traceback (most recent call last):
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1682, in <module>
    installer(args=sys.argv, log=sys.stdout)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 256, in __init__
    self.build_dependencies(packages=packages)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 780, in build_dependencies
    getattr(self, 'build_%s'%i)()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1028, in build_numpy
    confirm_import_module="numpy",
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 697, in build_python_module_pip
    self.verify_python_module(pkg_info['name'], confirm_import_module)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 520, in verify_python_module
    self.call("%s -c 'import %s'" % (python_exe, module_name))
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 359, in call
    return call(args, log=log, verbose=self.verbose, **kwargs)
  File "/scratch/roy/programs/phenix-1.16-3549/modules/cctbx_project/libtbx/auto_build/installer_utils.py", line 53, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to '/scratch/roy/programs/phenix-1.16-3549/base/bin/python -c 'import numpy'' failed with exit code 1
Process failed with return code 1

===========================================================================

Thanks in advance 
Rajeev

**Comment by hokru** [comment] 2019-07-25 13:59
Hi Rajeev,

Is this the error from running the bootstrap?
`phenix.python modules/cctbx_project/libtbx/auto_build/bootstrap.py --builder=qrefine` ?
phenix installation was all OK?

Kindly also let us know which linux distro/mac version this is.

`Original error was: /scratch/roy/programs/phenix-1.16-3549/conda_base/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS4_FromObject`
This suggest incompatible python unicode versions, possibly caused by a mixture of phenix.python and local python.

**Comment by rajeevroy09** [comment] 2019-07-25 14:27
Hi,

Thank you very much for your response.

-----Is this the error from running the bootstrap?---
"Yes, the error generated after running the bootstrap.
"$phenix.python modules/cctbx_project/libtbx/auto_build/bootstrap.py --builder=qrefine" 

-----phenix installation was all OK?--------
"Yes, the phenix installation is all OK, I using phenix since last 6 months. I have installed the current version "phenix-installer-1.16-3549-intel-linux-2.6-x86_64-centos6" just a week back."


-----------------linux distro/mac version this is?--------------------
    "                version: 1.16-3549
                     machine type: intel-linux-2.6-x86_64
                     OS version: 4.8.0-58-generic
                     destination: /scratch/roy/programs/phenix-1.16-3549
                     # of processors: 8"

-------------------Original error was: /scratch/roy/programs/phenix-1.16-3549/conda_base/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS4_FromObject
This suggest incompatible python unicode versions, possibly caused by a mixture of phenix.python and local python.-----------------------------------------------------------------------------------
 "Shall I just use "python modules/cctbx_project/libtbx/auto_build/bootstrap.py --builder=qrefine" instead of "phenix.python modules/cctbx_project/libtbx/auto_build/bootstrap.py --builder=qrefine"..?? 

Please suggest me, how I can overcome this error?

Best regards,
Rajeev

**Comment by hokru** [comment] 2019-07-25 14:35
Tagging the bootstrap expert @nwmoriarty 

Otherwise you can try to proceed manually:
```
  phenix.python -m pip install ase
  phenix.python -m pip install JPype1
  phenix.python -m pip install pymongo
  git clone https://github.com/qrefine/qrefine.git modules/qrefine (may exist already)
  libtbx.configure qrefine
```

**Comment by rajeevroy09** [comment] 2019-07-25 15:38
Hi, 

I am finally able to install it using manual method:

$phenix.python -m pip install ase < this command was throwing error because the recent ase 3.18.0 version requires python 3.5 or higher, so instead of installing ase 3.18.0, I have installed ase 3.17.0 and it worked>....so, the command i used here is...$phenix.python -m pip install ase==3.17.0.

The rest commands were ok.

Thanks for your help.
Rajeev

**Comment by hokru** [comment] 2019-07-25 16:03
Great! Once phenix makes the python3 jump, qrefine will follow.

Make sure to run the tests and check the documentation at https://qrefine.com/qr.html

The installation issue with bootstrap might be difficult to solve and specific to your setup. If everything works for you, feel free to close this issue.

**Comment by rajeevroy09** [comment] 2019-07-29 12:52
Hi, 

I ran the test as per the guidelines "https://github.com/qrefine/qrefine". Though the most of the tests ran fine, the test number 15, 16 and 38 always shows the failed status. I am attaching a log file for your reference.

[qr_test.log](https://github.com/qrefine/qrefine/files/3442280/qr_test.log)

Best regards,
Rajeev

**Closed as completed** 2019-07-30 09:06 UTC
