### ISSUE TITLE
qr.test failed, phenix-1.13-2998, CentOS 6

### ISSUE THREAD

**Issue by kaoweichun** [qrefine/qrefine#18] opened 2018-09-07 11:21 UTC
Hello, I installed qrefine using the command 

phenix.python modules/cctbx_project/libtbx/auto_build/bootstrap.py --builder=qrefine --nproc=8

in the existing phenix-1.13-2998 directory.  However when I ran qr.test the system wrote a series of errors (see file attached). The system is CentOS 6.6.

[qrefine_test.log](https://github.com/qrefine/qrefine/files/2360798/qrefine_test.log)
 
Has anybody a clue how to proceed with this ? Thanks.

**Comment by hokru** [comment] 2018-09-07 11:41
Hi. Please try running the `qr.test` command in an empty directory.

**Comment by kaoweichun** [comment] 2018-09-07 11:44
Yes, I created an empty directory, ran `qr.test` therein, and I got that result.

**Comment by nwmoriarty** [comment] 2018-09-07 15:55
Are you redirecting the output to a file called log?

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by kaoweichun** [comment] 2018-09-07 17:14
Yes, I did it on purpose for providing a log file here. I noticed that I ran `qr.test` the twice in order to get the log file so it complains the existing files. Here attached please find the new log file I copied from the standard output.

[log.txt](https://github.com/qrefine/qrefine/files/2361899/log.txt)

**Comment by nwmoriarty** [comment] 2018-09-07 23:04
Great!

So some of the errors are due to 1.13 so update to Phenix 1.14. Can you try
that and we'll see what is left to correct.

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by kaoweichun** [comment] 2018-09-08 17:57
Hi, 

thanks for the tip. I installed phenix-1.14.3247 with qrefine on CentOS6 and the log file of `qr.test` is attached.
[qr.log](https://github.com/qrefine/qrefine/files/2363571/qr.log)
 This time not all, but there are few steps failed.

WCK

**Comment by nwmoriarty** [comment] 2018-09-08 18:06
OK. So this error

tst_07 FAILED java.lang.RuntimeException: Class org.wallerlab.yoink.Yoink
not found

can mean you don't have a current version of Java. I had to install a
recent version (1.8 or so) and set it as the current version

setenv JAVA_HOME `/usr/libexec/java_home -v 1.8.0_144, x86_64`



Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by kaoweichun** [comment] 2018-09-08 18:41
Good, I updated java via `yum install java-1.8.0-openjdk-devel` and ran `qr.test` again. Indeed updating java resolved the test_07 FAILED and related issues. Now test 10 and test 13 are skipped (see [qr.test.log](https://github.com/qrefine/qrefine/files/2363607/qr.test.log)). 

I consider that `qr.test` is probably fine, so I proceeded to run `qr.finalise --example`, and it failed. See part 1 of [qr.finalise.log](https://github.com/qrefine/qrefine/files/2363614/qr.finalise.log). I am not sure if this is related to the test 10 and test 13 issue. If I just run `qr.finalise` then the program could at least be started (see part 2 of the log above) but of course nothing could be proceeded.

WCK

**Comment by nwmoriarty** [comment] 2018-09-08 19:18
So, --example seems broken but you should be able to move forward. Do you
have a model you wish to refine?

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by kaoweichun** [comment] 2018-09-08 19:48
Yes, so I started `qr.refine --help` and the program printed the phenix eff file but was somehow interrupted (see [qr.refine.log](https://github.com/qrefine/qrefine/files/2363656/qr.refine.log). I truncated the first few lines till the parallel section). 

If I just continue with `qr.refine input.mtz input.pdb`, then the program said "MOPAC command not specified" and it couldn't continue (sorry I didn't try to find/ read further documentations but just wanted to see if something could happen by providing a data and a model to it like phenix.refine).

Another issue is, the aforementioned CentOS6 machine is my test workstation. Now I wanted to install qrefine on my CentOS7 server which is equipped with more cores (is qrefine fully parallised?). Unfortunately the standard installation couldn't proceed ([qr.install.log](https://github.com/qrefine/qrefine/files/2363666/qr.install.log)).

WCK

**Comment by nwmoriarty** [comment] 2018-09-08 19:54
It is parallel and queue able but you are best to use a normal installer
not the bootstrap for the main Phenix installation.

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by kaoweichun** [comment] 2018-09-08 21:04
That sounds interesting so it can work with openmp and sge. My phenix-1.14.3247 is installed via the command line installer, and the qrefine is via bootstrap.

WCK

**Comment by nwmoriarty** [comment] 2018-09-09 16:01
I recommend the normal installer for Phenix and the bootstrap install for
QRefine. Simpler and easier.

BTW, it uses Python multiprocessor not openmp.

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by kaoweichun** [comment] 2018-10-06 11:32
Hi, I have updated phenix to 1.14-3260, and I can reproduce all the previous tests discussed in this thread. I am trying to run a qr.refine with a protein coordinate and x-ray data, and I got the following message (only the last few lines I think which is relevant).  Does that mean I must have one of the quantum engine installed so that I can use one of them? 

Thanks

WCK

#####

Initial r_work=0.1881 r_free=0.1864

Setting QM defaults
  Setting QM method to PM7


***********************************************************
restart info will be stored in /home/wekao/data5/171013_P13/x1_13keV/phenix_cml/pdb/input.rst.pickle
***********************************************************

Start:
     0 Rw: 0.1881 Rf: 0.1864 Rf-Rw: -0.0017 rmsd(b):  0.0159 rws:  1.000 n_fev: 0
Optimal weight search:
MOPAC command not specified
Sorry: Failed to get weight

**Comment by mpwaller** [comment] 2018-10-07 00:27
Daer WCK,

Correct, you need to to have MOPAC installed. Then you can just create an environment variable called MOPAC_COMMAND to point to the location of your MOPAC installation. 

Please send us an update when that next step works.

Cheers,
Mark

**Comment by kaoweichun** [comment] 2018-10-08 15:43
Dear Mark,

thanks for the hint. I installed MOPAC2016 for CentOS6 (the non-GPU version) and I could execute MOPAC with the supplied example dataset with success. However when I re-ran qr.refine, it did not complain the MOPAC command not specified but uttered

Optimal weight search:
[Errno 13] Permission denied
Sorry: Failed to get weight

I installed MOPAC in my personal directory (not the default /opt/mopac) but all the environmental variables have been adjusted accordingly (including LD_LIBRARY_PATH, MOPAC_LICENSE and MOPAC_COMMAND), so I think the permission denied issue is perhaps not relevant to MOPAC?

Best,
WCK

**Comment by nwmoriarty** [comment] 2018-10-08 15:55
Set this env. var. to 1 (for example in tcsh)

setenv LIBTBX_DISABLE_TRACEBACKLIMIT 1

and rerun.

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by kaoweichun** [comment] 2018-10-08 16:34
Hello,

I updated my .bashrc (export LIBTBX_DISABLE_TRACEBACKLIMIT=1) and I got the following result

Optimal weight search:
[Errno 13] Permission denied
Traceback (most recent call last):
  File "/home/programs/phenix-1.14-3260/build/../modules/qrefine/command_line/refine.py", line 123, in <module>
    run(args=sys.argv[1:], log=log)
  File "/home/programs/phenix-1.14-3260/build/../modules/qrefine/command_line/refine.py", line 118, in run
    log      = log)
  File "/home/programs/phenix-1.14-3260/modules/qrefine/qr.py", line 438, in run
    results               = results_manager)
  File "/home/programs/phenix-1.14-3260/modules/qrefine/driver.py", line 305, in refine
    raise Sorry("Failed to get weight")
Sorry: Failed to get weight

Thanks,
WCK

**Comment by nwmoriarty** [comment] 2018-10-08 16:36
OK, I would remove it now. It looks like you are trying to write into a
directory that does not have the correct writing permission.

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by kaoweichun** [comment] 2018-10-08 16:46
to remove (?), please advise how to proceed (reinstall qr refine after you have fixed something or?)

Best,
WCK

**Comment by mpwaller** [comment] 2019-01-17 12:48
Dear WCK,

did you get the calculation running?

Cheers,
Mark

**Comment by kaoweichun** [comment] 2019-01-17 21:34
Dear Mark,

unfortunately not. I have tried again with the latest phenix build today and I still got the Permission denied error message (although the cause might be different?).  Details see below:

WCK

***********************************************************

Start:
     0 Rw: 0.1881 Rf: 0.1864 Rf-Rw: -0.0017 rmsd(b):  0.0157 rws:  1.000 n_fev: 0
Optimal weight search:
Traceback (most recent call last):
  File "/home/programs/phenix-dev-3386/build/../modules/qrefine/command_line/refine.py", line 119, in <module>
    run(args=sys.argv[1:], log=log)
  File "/home/programs/phenix-dev-3386/build/../modules/qrefine/command_line/refine.py", line 114, in run
    log      = log)
  File "/home/programs/phenix-dev-3386/modules/qrefine/qr.py", line 502, in run
    results               = results_manager)
  File "/home/programs/phenix-dev-3386/modules/qrefine/driver.py", line 470, in refine
    calculator.calculate_weight(verbose=params.debug)
  File "/home/programs/phenix-dev-3386/modules/qrefine/calculator.py", line 200, in calculate_weight
    verbose = verbose)
  File "/home/programs/phenix-dev-3386/modules/qrefine/calculator.py", line 95, in compute_weight
    tc, gc = rm.target_and_gradients(sites_cart=xrs.sites_cart())
  File "/home/programs/phenix-dev-3386/modules/qrefine/restraints.py", line 239, in target_and_gradients
    define_str=define_str, # for Turbomole
  File "/home/programs/phenix-dev-3386/modules/qrefine/plugin/ase/mopac_qr.py", line 334, in run_qr
    self.run()
  File "/home/programs/phenix-dev-3386/modules/qrefine/plugin/ase/mopac_qr.py", line 203, in run
    run_timeout(command_exc ,72000)# 20hours
  File "/home/programs/phenix-dev-3386/modules/qrefine/plugin/ase/mopac_qr.py", line 179, in run_timeout
    stderr=subprocess.PIPE)
  File "/home/programs/phenix-dev-3386/base/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/programs/phenix-dev-3386/base/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by hokru** [comment] 2019-01-19 04:41
Something is wrong with setting up mopac correctly. The variable should point to the binary, not the directory.  The error says there are missing permissions to execute the binary specified MOPAC_COMMAND

How does MOPAC_COMMAND look like?
`echo $MOPAC_COMMAND`

**Comment by kaoweichun** [comment] 2019-01-19 15:35
Originally my MOPAC_COMMAND was pointed to /home/programs/mopac/, after your hint I changed it to /home/programs/mopac/MOPAC2016.exe. I reloaded my .bashrc and ran qr.refine again (`qr.refine model.pdb data.mtz`), I got the following error message. By the way, I do get ./ase/tmp_ase.mop and ./ase/tmp_ase.pdb. 

WCK

***********************************************************

Start:
     0 Rw: 0.1881 Rf: 0.1864 Rf-Rw: -0.0017 rmsd(b):  0.0157 rws:  1.000 n_fev: 0
Optimal weight search:
Traceback (most recent call last):
  File "/home/programs/phenix-dev-3386/build/../modules/qrefine/command_line/refine.py", line 119, in <module>
    run(args=sys.argv[1:], log=log)
  File "/home/programs/phenix-dev-3386/build/../modules/qrefine/command_line/refine.py", line 114, in run
    log      = log)
  File "/home/programs/phenix-dev-3386/modules/qrefine/qr.py", line 502, in run
    results               = results_manager)
  File "/home/programs/phenix-dev-3386/modules/qrefine/driver.py", line 470, in refine
    calculator.calculate_weight(verbose=params.debug)
  File "/home/programs/phenix-dev-3386/modules/qrefine/calculator.py", line 200, in calculate_weight
    verbose = verbose)
  File "/home/programs/phenix-dev-3386/modules/qrefine/calculator.py", line 95, in compute_weight
    tc, gc = rm.target_and_gradients(sites_cart=xrs.sites_cart())
  File "/home/programs/phenix-dev-3386/modules/qrefine/restraints.py", line 239, in target_and_gradients
    define_str=define_str, # for Turbomole
  File "/home/programs/phenix-dev-3386/modules/qrefine/plugin/ase/mopac_qr.py", line 334, in run_qr
    self.run()
  File "/home/programs/phenix-dev-3386/modules/qrefine/plugin/ase/mopac_qr.py", line 209, in run
    self.version = self.read_version(foutput)
  File "/home/programs/phenix-dev-3386/modules/qrefine/plugin/ase/mopac_qr.py", line 220, in read_version
    lines = open(fname).readlines()
IOError: [Errno 2] No such file or directory: './ase/tmp_ase.out'

**Comment by hokru** [comment] 2019-01-20 06:53
something is wrong with running mopac on the input file as the output is not being written.
Can you please check if it works manually: `MOPAC2016.exe ./ase/tmp_ase.mop`

**Comment by kaoweichun** [comment] 2019-01-20 08:37
Yes. This command starts geometry optimization, and generats tmp_ase.end, tmp_ase.aux, tmp_ase.out in the ase directory and fortmb3A9p in the project directory. 

The computation has taken more than 30 mins and doesn't seem to stop. 27 GB of the RAM is used (which is still below 10% of the physical RAM installed). The test data is a 50 kDa protein with some 700 water molecules. Perhaps it's too large? I am now changing the number or threads to 24 and see if it can finish quicker.

Below is the relevant section of my .bashrc, hope that it will help to diagnose the issue.

WCK

********************

alias mopac='/home/programs/mopac/MOPAC2016.exe'
export PATH=$PATH:/home/programs/mopac
export LD_LIBRARY_PATH=/home/programs/mopac/
export MOPAC_LICENSE=/home/programs/mopac/

export MOPAC_COMMAND=/home/programs/mopac/MOPAC2016.exe
export LIBTBX_DISABLE_TRACEBACKLIMIT=1

**Comment by hokru** [comment] 2019-01-20 10:01
You will want to use the fragmentation approach (divide & conquer sense) using `clustering=true`. This divides the large protein into smaller structures that are more manageable for QM methods. You can submit the calculation of the clusters to a SGE queue using `parallel.method=sge` (see other `parallel` keywords for config details) 

No immediate idea why mopac is not run correctly through qrefine. It makes a system call to the command you executed manually. I cannot reproduce the error on my machine.

**Comment by kaoweichun** [comment] 2019-01-20 11:06
Perhaps there is a more fundamental issue of the installation? For instance in order to enable clustering and parallel methods, I tried to run `qr.refine --help` to list all options, it first listed all parameters and stopped, showing few error messages after `dump_gradients = None`.  Apparently something is not running properly.
 
*****

Traceback (most recent call last):
  File "/home/programs/phenix-dev-3386/build/../modules/qrefine/command_line/refine.py", line 119, in <module>
    run(args=sys.argv[1:], log=log)
  File "/home/programs/phenix-dev-3386/build/../modules/qrefine/command_line/refine.py", line 58, in run
    pdb_file_name    = cmdline.pdb_file_names[0],
IndexError: list index out of range

**Comment by hokru** [comment] 2019-01-20 11:17
That is, or was, expected behaviour.

`qr.refine --help` was added earlier today. You can go to into `$PHENIX/modules/qrefine` and issue a `git pull`.

 `qr.refine --defaults` will print the list of arguments that are explained here [docs](https://qrefine.com/qr.html)

**Comment by kaoweichun** [comment] 2019-01-20 11:30
I issued `git pull` in the installation directory, ran `qr.refine --defaults` and redirected the stdout to `refine.params`, modified it, and executed `qr.refine refine.params`. It first listed all parameters and stopped, seems to be the same behavior as I ran `qr.refine --help` before.  Maybe I am not doing it correctly?

***********

Traceback (most recent call last):
  File "/home/programs/phenix-dev-3386/build/../modules/qrefine/command_line/refine.py", line 144, in <module>
    run(args=sys.argv[1:], log=log)
  File "/home/programs/phenix-dev-3386/build/../modules/qrefine/command_line/refine.py", line 82, in run
    pdb_file_name    = cmdline.pdb_file_names[0],
IndexError: list index out of range

**Comment by mpwaller** [comment] 2019-01-21 05:46
You don't need to print out defaults and use them as an input. They are just there in case you want to know what parameters are used. Just a shortcut to stop having to look into the code itself.

Try and create a new folder with just your .pdb file and .mtz file.

To carry out an optimization (you don't need the .mtz file).
To override a parameter add it to  the command line eg:

`qr.refine example.pdb mode=opt restraints=cctbx`

Now you cant try a simple refinement:

`qr.refine example.pdb example.mtz  restraints=cctbx`

This will now perform a classical refinement using the cctbx restraints. It should be super fast. 

Once you can confirm this works, try and go back to mopac.

`qr.refine example.pdb mode=opt restraints=qm `

I think these steps should help you see how it works.

Please keep us updated!

**Comment by kaoweichun** [comment] 2019-01-21 15:17
The first two commands were executed and finished normally, without any error messages. A directory pdb was created and several coordinate files were written.

When I performed the third command it stopped at the same error message as before:  No such file or directory `./ase/tmp_ase.out`. As suggested by hokru, I could manually run mopac but it's not called from `qr.refine`.

**Comment by hokru** [comment] 2019-01-22 09:55
I manage to reproduce the error on my linux workstation. There are two issues, one is easy to fix and the other is more problematic. I'll make another post soon, with at least a workaround, if I cannot fully fix it quickly.

**Comment by hokru** [comment] 2019-01-22 13:19
The issue you are facing is decribed in the issue linked above. I uploaded an updated mopac interface.

Please pull the new qrefine version and set `export MOPAC_DIR=/home/programs/mopac/`.
This adds the `LD_PRELOAD` prefix as described automatically.

 Let us know if it works.

**Comment by kaoweichun** [comment] 2019-01-22 21:32
Thanks for the effort to make it working and found the solution. mopac is running under qrefine. I tried three different approaches: 

1. I could execute all three commands as suggested mpwaller, and it is still running.

2. I simply ran `qrefine data.mtz model.pdb` and the calculation could be started without problem. As the coordinate contains 3843 atoms, the computation takes long, thus I tried the approach hokru suggested:

3.  I executed `qr.refine data.mtz model.pdb clustering=true`. The job could start but end up in the following error message. Perhaps it has nothing to do with mopac as the ase directory had not been created.

********

Traceback (most recent call last):
  File "/home/programs/phenix-dev-3386/build/../modules/qrefine/command_line/refine.py", line 144, in <module>
    run(args=sys.argv[1:], log=log)
  File "/home/programs/phenix-dev-3386/build/../modules/qrefine/command_line/refine.py", line 138, in run
    log      = log)
  File "/home/programs/phenix-dev-3386/modules/qrefine/qr.py", line 451, in run
    crystal_symmetry = model.xray_structure.crystal_symmetry())
  File "/home/programs/phenix-dev-3386/modules/qrefine/qr.py", line 296, in create_fragment_manager
    charge_cutoff              = params.cluster.charge_cutoff)
  File "/home/programs/phenix-dev-3386/modules/qrefine/fragment.py", line 95, in __init__
    self.set_up_cluster_qm()
  File "/home/programs/phenix-dev-3386/modules/qrefine/fragment.py", line 144, in set_up_cluster_qm
    self.get_fragment_hierarchies_and_charges()
  File "/home/programs/phenix-dev-3386/modules/qrefine/fragment.py", line 393, in get_fragment_hierarchies_and_charges
    original_pdb_filename=self.expansion_file)
  File "/home/programs/phenix-dev-3386/modules/qrefine/completion.py", line 1062, in run
    verbose=False,
  File "/home/programs/phenix-dev-3386/modules/qrefine/completion.py", line 1003, in complete_pdb_hierarchy
    verbose=verbose,
  File "/home/programs/phenix-dev-3386/modules/qrefine/completion.py", line 651, in add_terminal_hydrogens
    append_to_end_of_model=append_to_end_of_model,
  File "/home/programs/phenix-dev-3386/modules/qrefine/completion.py", line 567, in iterate_using_original
    append_to_end_of_model=append_to_end_of_model,
  File "/home/programs/phenix-dev-3386/modules/qrefine/completion.py", line 279, in add_c_terminal_oxygens_to_residue_group
    c_ca_n = [c, ca, n],
  File "/home/programs/phenix-dev-3386/modules/qrefine/completion.py", line 234, in add_c_terminal_oxygens_to_atom_group
    dihedral = dihedral_angle(sites=[atom.xyz,
AttributeError: 'NoneType' object has no attribute 'xyz'

**Comment by nwmoriarty** [comment] 2019-01-23 00:58
Can you send the input files?

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by mpwaller** [comment] 2019-01-23 02:46
@kaoweichun When you use clustering=true you must also turn on gradient_only=true. Another thing to consider is setting the stpmax=0.2. I have just updated the default in qr, so you can either pull the latest version, or simply add the stpmax=0.2 as an argument. Please still send your inputs to @nwmoriarty  to debug your problem.

**Comment by kaoweichun** [comment] 2019-01-23 16:31
Thanks for the update. I will contact @nwmoriarty off-list regarding to the inputs. I think the main  issue of this thread (installation and mopac) has been resolved and for other problems we can create new topics accordingly.

**Comment by hokru** [comment] 2019-01-23 17:11
Thanks for being patient with us to solve this initial technical problem. Closing the issue. Feel free to re-open if the need arises.

**Closed as completed by hokru** 2019-01-23 17:11 UTC
